# Multidimensional Numpy Arrays

Numpy arrays can have more than one dimension. One way to
create such an array is to start with a 1-dimensional array and use the
numpy `reshape()` function that rearranges elements of that array into
a new shape.

In [2]:
import numpy as np

a = np.arange(12)   # the array to be reshaped
b = a.reshape(3,4)  # reshape a into 3 rows and 4 columns
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


`b` is a 2-dimensional array with 3 rows and 4 columns. We can access its elements of specifying row and column indexes:

In [6]:
# get the element in row 0 and column 2
print(b[0, 2])

2


In [7]:
b[0,2] = 100
print(b)

[[  0   1 100   3]
 [  4   5   6   7]
 [  8   9  10  11]]


The functions `np.full()`, `np.zeros()`, `np.ones()` and `np.empty()` can be
used to create arrays with more than one dimension:

In [8]:
# create an array with 4 rows and 5 columns
c = np.ones((4,5)) 
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Mathematical operations on multidimensional arrays

Mathematical operations on multidimensional arrays work similarly as for
1-dimensional arrays.

In [10]:
a = np.arange(1, 5).reshape(2,2)
b = np.full((2,2), fill_value = 10)

print(f"a = \n{a}\n")
print(f"b = \n{b}")

a = 
[[1 2]
 [3 4]]

b = 
[[10 10]
 [10 10]]


In [11]:
# multiplication by a number
5*a

array([[ 5, 10],
       [15, 20]])

In [13]:
# addition of two arrays of the same shape
a+b 

array([[11, 12],
       [13, 14]])

In [14]:
# multiplication of two arrays of the same shape
a*b 

array([[10, 20],
       [30, 40]])

Notice that array multiplication multiplies corresponding elements of
arrays. In order to perform matrix multiplication of 2-dimensional
arrays, we can use the numpy `@` operator:

In [15]:
# matrix product of 2-dimensional arrays
a@b

array([[30, 30],
       [70, 70]])

Mathematical functions defined by numpy can be applied to
multidimensional arrays:

In [18]:
# compute cosine of every element
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

## Slicing multidimensional arrays

To create a slice of a multidimensional array, we need to specify which part of each dimension we want to select:

In [20]:
# create a 5x6 array
a = np.arange(30).reshape(5,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [21]:
#select elements in rows 1-3 and columns 0-1
b = a[1:4, 0:2] 
print(b)


[[ 6  7]
 [12 13]
 [18 19]]


In [22]:
#select elements in rows 0-2 and columns 2-3
c = a[:3, 2:4] 
print(c)

[[ 2  3]
 [ 8  9]
 [14 15]]


In [23]:
# select all elements in column 0
d = a[:, 0] 
print(d)

[ 0  6 12 18 24]


**Note.** `a[i]` is equivalent to `a[i,:]` i.e. it selects the i-th row of an array:

In [24]:
# select all elements in row 1
print(a[1])

[ 6  7  8  9 10 11]


Similarly as for 1-dimensional arrays, slicing produces a view of the original array, and changing a slice changes the original array:

In [25]:
b = a[:3, :3]   # create a slice
b[0,0] = 1000   # changing a slice changes the original array as well

print(f"b = \n{b}\n")
print(f"a = \n{a}")

b = 
[[1000    1    2]
 [   6    7    8]
 [  12   13   14]]

a = 
[[1000    1    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20   21   22   23]
 [  24   25   26   27   28   29]]


We can use this to change several entries of an array at once:

In [26]:
a[:4, :4] = 0  # set all entries of the slice to 0
print(a)

[[ 0  0  0  0  4  5]
 [ 0  0  0  0 10 11]
 [ 0  0  0  0 16 17]
 [ 0  0  0  0 22 23]
 [24 25 26 27 28 29]]


## Sorting

Numpy has several functions for creating arrays with randomly selected entries.

In [4]:
# initialize random number generator
rng = np.random.default_rng(0)
# create 1-dimensional array of 5 elements with random integer 
# entries between 0  and 9
a = rng.integers(0, 10, size=5)
a

array([8, 6, 5, 2, 3])

In [40]:
# create 4x5 array with random integer entries between -10  and 11
b = rng.integers(-10, 11, size=(4, 5))
print(b)

[[ 9 -6 -1 -5  8]
 [-8  4  9 -4 -5]
 [ 6  2  1  8 -9]
 [-5 -2  9 -9 -1]]


For a 1-dimensional array `a` the function `np.sort(a)` sorts elements of the array from the smallest to the largest:

In [41]:
np.sort(a)

array([2, 3, 5, 6, 8])

For multidimensional arrays, `np.sort()` takes an additional `axis` argument which specifies the coordinate axis along which the sort is to be performed: 

In [45]:
# sort b along axis 0, i.e. sort values of each column
np.sort(b, axis=0)

array([[-8, -6, -1, -9, -9],
       [-5, -2,  1, -5, -5],
       [ 6,  2,  9, -4, -1],
       [ 9,  4,  9,  8,  8]])

In [46]:
# sort b along axis 1, i.e. sort values of each row
np.sort(b, axis=1)

array([[-6, -5, -1,  8,  9],
       [-8, -5, -4,  4,  9],
       [-9,  1,  2,  6,  8],
       [-9, -5, -2, -1,  9]])

Using `np.sort()` without the `axis` argument sorts the array along its last axis: 

In [47]:
# the same as sorting along axis 1
np.sort(b)

array([[-6, -5, -1,  8,  9],
       [-8, -5, -4,  4,  9],
       [-9,  1,  2,  6,  8],
       [-9, -5, -2, -1,  9]])

The function `np.argsort(a)` is similar to `np.sort`, but instead of returning sorted values of `a` it produces an array of indices showing how the entries of the array should be rearranged to be sorted:

In [50]:
print("a:")
print(a)
print("\nnp.argsort(a):")
print(np.argsort(a))

a:
[8 6 5 2 3]

np.argsort(a):
[3 4 2 1 0]


In [49]:
print("b:")
print(b)
print("\nnp.argsort(b, axis=1):")
print(np.argsort(b, axis=1))

b:
[[ 9 -6 -1 -5  8]
 [-8  4  9 -4 -5]
 [ 6  2  1  8 -9]
 [-5 -2  9 -9 -1]]

np.argsort(b, axis=1):
[[1 3 2 4 0]
 [0 4 3 1 2]
 [4 2 1 0 3]
 [3 0 1 4 2]]


## Aggregation functions

Numpy includes several aggregation functions that summarize, in various ways, data contained in an array. 

In [51]:
# create a 3x4 array of randomly selected integers between 0 and 19
a = rng.integers(0, 20, size=(3, 4))
print(a)

[[ 9  0  8 12]
 [ 8  6 11 19]
 [ 2  5 18  5]]


Compute the sum of all array entries:

In [52]:
a.sum()

103

Computer the average value of array entries:

In [53]:
a.mean()

8.583333333333334

Compute the minimum and maximum values of the array:

In [54]:
a.min(), a.max()

(0, 19)

Aggregate functions can be used with an additional `axis` argument, which indicates that the function should be applied along one coordinate axis of the array. For example, `a.sum(axis = 0)` computes the sum of each column of the array:  

In [57]:
a.sum(axis=0)

array([19, 11, 37, 36])

Similarly, `a.sum(axis = 1)` computes the sum of each row:

In [58]:
a.sum(axis=1)

array([29, 44, 30])