# Numpy fancy indexing

Fancy indexing is a feature of numpy arrays that lets us provide to an array a list of indices instead of a single index. This selects all array elements with indices on the list.

In [2]:
import numpy as np

# create an array of 10 random integers between 0 and 99
rng = np.random.default_rng(0)
a = rng.integers(0, 100, 10)
print(a)

[85 63 51 26 30  4  7  1 17 81]


In [3]:
# select elements with indexes 1, 5, and 6
a[[1, 5, 6]]

array([63,  4,  7])

Fancy indexing works with multidimensional arrays as well:

In [4]:
b = np.arange(20).reshape(4, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [5]:
# select rows 1 and 3
b[[1, 3]]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [10]:
# select columns 0,1, and 4
b[:, [0, 1, 4]]

array([[ 0,  1,  4],
       [ 5,  6,  9],
       [10, 11, 14],
       [15, 16, 19]])

Given a 2-dimensional array `b` the code `b[[1, 2, 3], [1, 4, 4]]` selects elements `b[1,1]`, `b[2,4]`, and `b[3,4]`:

In [6]:
b[[1, 2, 3], [1, 4, 4]]

array([ 6, 14, 19])

Just as with other indexing schemes, we can use fancy indexing to modify several entries of an array at once:

In [7]:
b[[1, 2, 3], [1, 4, 4]] = 1000
print(b)

[[   0    1    2    3    4]
 [   5 1000    7    8    9]
 [  10   11   12   13 1000]
 [  15   16   17   18 1000]]


Fancy indexing can be mixed with other forms of indexing. For example, we can apply fancy indexing to one axis of an array, and slicing to the second axis:

In [8]:
b = np.arange(20).reshape(4, 5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [9]:
# select elements which are in rows 1, 3 and columns 0-2
b[[1, 3], :3]

array([[ 5,  6,  7],
       [15, 16, 17]])

## Fancy indexing example

Here is an example of how fancy indexing can be used in practice. Lets say that we have a numpy array that in the first column gives student id numbers, and in the second column their exam scores:

In [10]:
rng = np.random.default_rng(0)
exam_scores = np.array([np.arange(5000, 5010), rng.integers(0, 100, 10)]).T
print(exam_scores)

[[5000   85]
 [5001   63]
 [5002   51]
 [5003   26]
 [5004   30]
 [5005    4]
 [5006    7]
 [5007    1]
 [5008   17]
 [5009   81]]


Assume that we want to sort rows of this array in the increasing order of exam scores. Applying the numpy `argsort()` function to the score column gives an array that shows how row indexes should be arranged to give such an ordering:

In [11]:
indices = np.argsort(exam_scores[:, 1])
print(indices)

[7 5 6 8 3 4 2 1 9 0]


Fancy indexing lets us apply this to sort the array with exam scores:

In [12]:
print(exam_scores[indices])

[[5007    1]
 [5005    4]
 [5006    7]
 [5008   17]
 [5003   26]
 [5004   30]
 [5002   51]
 [5001   63]
 [5009   81]
 [5000   85]]
