# Numpy Boolean arrays

A Boolean array is a numpy array with Boolean (True/False) values. Such
array can be obtained by applying a logical operator to another numpy
array:

In [2]:
import numpy as np

# create a 4x4 array of integers
a = np.arange(16).reshape(4, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
# test which elements of a are greated than 5
large_values = (a > 5)
print(large_values)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [4]:
# test which elements of a are even
even_values = (a%2 == 0) 
print(even_values)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [5]:
# another 4x4 array
b = np.reshape(np.arange(21, 5, -1), (4, 4))
print(b)

[[21 20 19 18]
 [17 16 15 14]
 [13 12 11 10]
 [ 9  8  7  6]]


In [6]:
# test which elements of a are greater than the corresponding elements of b
equals = (a > b)
print(equals)

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]]


## Logical operations on Boolean arrays

Boolean arrays can be combined using logical operators:


| operator | meaning                  |
|----------|--------------------------|
| `~`      | negation (logical "not") |
| `&`      | logical "and"            |
| `\|`      | logical "or"             |


In [6]:
# test which elements of a are not divisible by 3
b = ~(a%3 == 0) 

print(f"a=\n{a}\n")
print(f"b=\n{b}")

a=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

b=
[[False  True  True False]
 [ True  True False  True]
 [ True False  True  True]
 [False  True  True False]]


In [7]:
# test which elements of a are divisible by either 2 or 3
c = (a%2 == 0) | (a%3 == 0)

print(f"a=\n{a}\n")
print(f"c=\n{c}")

a=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

c=
[[ True False  True  True]
 [ True False  True False]
 [ True  True  True False]
 [ True False  True  True]]


In [8]:
# test which elements of a are divisible by both 2 and 3
d = (a%2 == 0) & (a%3 == 0) 

print(f"a=\n{a}\n")
print(f"d=\n{d}")

a=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

d=
[[ True False False False]
 [False False  True False]
 [False False False False]
 [ True False False False]]


## Indexing with Boolean arrays

Boolean arrays can be used to select elements of other numpy arrays. If
`a` is any numpy array and `b` is a boolean array of the same
dimensions then `a[b]` selects all elements of `a` for which the
corresponding value of `b` is `True`.

In [9]:
# create a 4x4 array of integers
a = np.reshape(np.arange(16), (4, 4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
# test which elements of a are even
b = (a%2 == 0) 
b

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [11]:
# select all even elements of the array a
a[b] 

array([ 0,  2,  4,  6,  8, 10, 12, 14])

We can use Boolean indexing to modify elements of an array based on a logical condition:

In [12]:
# set values of all even elements of the array to 100
a[a%2 == 0] = 100 
a

array([[100,   1, 100,   3],
       [100,   5, 100,   7],
       [100,   9, 100,  11],
       [100,  13, 100,  15]])

In the next example we create two numpy arrays, `x` and `y`, and then use Boolean indexing to set
all entries of `x` that are smaller that the corresponding entries of `y` to -1:

In [3]:
# create two 3x3 arrays of random numbers
rng = np.random.default_rng(0)
x = rng.random((3, 3))
y = rng.random((3, 3))

print(f"x=\n{x}\n")
print(f"y=\n{y}")

x=
[[0.63696169 0.26978671 0.04097352]
 [0.01652764 0.81327024 0.91275558]
 [0.60663578 0.72949656 0.54362499]]

y=
[[0.93507242 0.81585355 0.0027385 ]
 [0.85740428 0.03358558 0.72965545]
 [0.17565562 0.86317892 0.54146122]]


In [5]:
x[x < y] = -1
x

array([[-1.        , -1.        ,  0.04097352],
       [-1.        ,  0.81327024,  0.91275558],
       [ 0.60663578, -1.        ,  0.54362499]])